fix: used existing copy to update Project because of ASP.NET exception.
System.InvalidOperationException: The instance of entity type 'Project' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.